# Restore a target temperature after restart local thermostat
- alias: 'Restores a target temperature after restart local thermostat (first floor) – corridor and toilet'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.first_floor_connection_of_thermostat_corridor_and_toilet
      from: 'off'
      to: 'on'
  action:
    - service: mqtt.publish
      data:
        topic: 'home/first-floor/corridor-and-toilet/required-temperature-from-system'
        payload_template: "{{ state_attr('climate.first_floor_corridor_and_toilet','temperature') | float }}"
        qos: 1
- alias: 'Restores a target temperature after restart local thermostat (first floor) – bathroom'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.first_floor_connection_of_thermostat_bathroom
      from: 'off'
      to: 'on'
  action:
    - service: mqtt.publish
      data:
        topic: 'home/first-floor/bathroom/required-temperature-from-system'
        payload_template: "{{ state_attr('climate.first_floor_bathroom','temperature') | float }}"
        qos: 1
- alias: 'Restores a target temperature after restart local thermostat (first floor) – living room and kitchen'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.first_floor_connection_of_thermostat_living_room_and_kitchen
      from: 'off'
      to: 'on'
  action:
    - service: mqtt.publish
      data:
        topic: 'home/first-floor/living-room-and-kitchen/required-temperature-from-system'
        payload_template: "{{ state_attr('climate.first_floor_living_room_and_kitchen','temperature') | float }}"
        qos: 1
- alias: 'Restores a target temperature after restart local thermostat (first floor) – cellar'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.first_floor_connection_of_thermostat_cellar
      from: 'off'
      to: 'on'
  action:
    - service: mqtt.publish
      data:
        topic: 'home/first-floor/cellar/required-temperature-from-system'
        payload_template: "{{ state_attr('climate.first_floor_cellar','temperature') | float }}"
        qos: 1
- alias: 'Restores a target temperature after restart local thermostat (first floor) – garage'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.first_floor_connection_of_thermostat_garage
      from: 'off'
      to: 'on'
  action:
    - service: mqtt.publish
      data:
        topic: 'home/first-floor/garage/required-temperature-from-system'
        payload_template: "{{ state_attr('climate.first_floor_garage','temperature') | float }}"
        qos: 1