- alias: 'Second floor – Sets required temperature for a corridor and toilet from system'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: climate.second_floor_corridor_and_toilet
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
            {{ trigger.from_state and
               trigger.to_state.attributes.temperature !=
               trigger.from_state.attributes.temperature and  is_state("input_boolean.second_floor_mqtt_req_temp_record_from_corridor_and_toilet", "off") }}
  action:
    - service: mqtt.publish
      data:
        topic: 'home/second-floor/corridor-and-toilet/required-temperature-from-system'
        payload_template: "{{ state_attr('climate.second_floor_corridor_and_toilet','temperature') | float }}"
        qos: 1
- alias: 'Second floor – Sets required temperature for a corridor and toilet from device'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.second_floor_corridor_and_toilet_required_temp_from_device
  condition:
    condition: template
    value_template: >
        {{ trigger.from_state and
           trigger.to_state !=
           trigger.from_state }}
  action:
    # Disable sets required temp. from system
    - service: input_boolean.turn_on
      entity_id: input_boolean.second_floor_mqtt_req_temp_record_from_corridor_and_toilet
    - service: climate.set_temperature
      entity_id: climate.second_floor_corridor_and_toilet
      data_template:
        temperature: '{{ states("sensor.second_floor_corridor_and_toilet_required_temp_from_device") }}'
    - delay: 
        milliseconds: 5
    - service: input_boolean.turn_off
      entity_id: input_boolean.second_floor_mqtt_req_temp_record_from_corridor_and_toilet