# Sensors for 18B20
- platform: template
  sensors:
    hot_water_tank_top:
      friendly_name: 'Zásobník vody horní čidlo'
      unit_of_measurement: '°C'
      value_template: '0'
    hot_water_tank_middle:
      friendly_name: 'Zásobník vody střední čidlo'
      unit_of_measurement: '°C'
      value_template: '0'
    hot_water_tank_bottom:
      friendly_name: 'Zásobník vody spodní čidlo'
      unit_of_measurement: '°C'
      value_template: '0'
    outdoor:
      friendly_name: 'Venkovní teplota'
      unit_of_measurement: '°C'
      value_template: '0'