# Settings a friendly name and value (on/off) for LED indication according to temp.
- platform: template
  sensors:
    blue_led:
      friendly_name: 'Modrá LED indikace'
      friendly_name_template: >-
        {% set led_indication_min_value_temp_top_sensor = states('input_number.led_indication_min_value_temp_top_sensor') | int %}
        {% if is_state('switch.blue_led', 'on') %}
          Hroní čidlo – teplota pod {{ led_indication_min_value_temp_top_sensor }} °C 
        {% else %}
          Hroní čidlo – teplota nad {{ led_indication_min_value_temp_top_sensor }} °C
        {% endif %}
      value_template: >-
        {% if is_state('switch.blue_led', 'on') %}
          Zapnuto
        {% else %}
          Vypnuto
        {% endif %}
      entity_picture_template: '/local/images/icons/blue-led.png'
    orange_led:
      friendly_name: 'Oranžová LED indikace'
      friendly_name_template: >-
        {% set led_indication_max_value_temp_middle_sensor = states('input_number.led_indication_max_value_temp_middle_sensor') | int %}
        {% if is_state('switch.orange_led', 'on') %}
          Střední čido – teplota nad {{ led_indication_max_value_temp_middle_sensor }} °C 
        {% else %}
          Střední čido – teplota pod {{ led_indication_max_value_temp_middle_sensor }} °C
        {% endif %}
      value_template: >-
        {% if is_state('switch.orange_led', 'on') %}
          Zapnuto
        {% else %}
          Vypnuto
        {% endif %}
      entity_picture_template: '/local/images/icons/orange-led.png'
    red_led:
      friendly_name: 'Červená LED indikace'
      friendly_name_template: >-
        {% set led_indication_max_value_temp_bottom_sensor = states('input_number.led_indication_max_value_temp_bottom_sensor') | int %}
        {% if is_state('switch.red_led', 'on') %}
          Spodní čidlo – teplota nad {{ led_indication_max_value_temp_bottom_sensor }} °C 
        {% else %}
          Spodní čidlo – teplota pod {{ led_indication_max_value_temp_bottom_sensor }} °C
        {% endif %}
      value_template: >-
        {% if is_state('switch.red_led', 'on') %}
          Zapnuto
        {% else %}
          Vypnuto
        {% endif %}
      entity_picture_template: '/local/images/icons/red-led.png'