# Sensors for thermostat
- platform: template
  sensors:
    thermostat_first_floor:
      friendly_name: 'Termostat přízemí'
      value_template: '1'
    thermostat_second_floor:
      friendly_name: 'Termostat patro'
      value_template: '1'
    thermostat_first_floor_display:
      friendly_name: 'Termostat přízemí'
      value_template: >-
        {% if is_state('sensor.thermostat_first_floor', '1') %}
          Zapnuto
        {% else %}
          Vypnuto
        {% endif %}
      entity_picture_template: >-
          {% if is_state('sensor.thermostat_first_floor', '1') %}
            /local/images/icons/floor-heating-on.png
          {% else %}
            /local/images/icons/floor-heating-off.png
          {% endif %}
    thermostat_second_floor_display:
      friendly_name: 'Termostat patro'
      value_template: >-
        {% if is_state('sensor.thermostat_second_floor', '1') %}
          Zapnuto
        {% else %}
          Vypnuto
        {% endif %}
      entity_picture_template: >-
          {% if is_state('sensor.thermostat_second_floor', '1') %}
            /local/images/icons/floor-heating-on.png
          {% else %}
            /local/images/icons/floor-heating-off.png
          {% endif %}