# Detection of state open window for second floor
- platform: trend
  sensors:
    second_floor_detection_of_open_window_bathroom:
      friendly_name: 'Detekce otevřeného okna – koupelna (druhé patro)'
      entity_id: sensor.second_floor_bathroom_temp
      sample_duration: 7200
      min_gradient: -0.001
      max_samples: 240
      device_class: window
    second_floor_detection_of_open_window_kitchen_workroom_living_and_diving_room:
      friendly_name: 'Detekce otevřeného okna – kuchyň, pracovna, bývací/jídelní pokoj (druhé patro)'
      entity_id: sensor.second_floor_kitchen_workroom_living_and_diving_room_temp
      sample_duration: 7200
      min_gradient: -0.001
      max_samples: 240
      device_class: window
    second_floor_detection_of_open_window_thomas_bedroom:
      friendly_name: 'Detekce otevřeného okna – Tomáš ložnice (druhé patro)'
      entity_id: sensor.second_floor_thomas_bedroom_temp
      sample_duration: 7200
      min_gradient: -0.001
      max_samples: 240
      device_class: window
    second_floor_detection_of_open_window_north_room:
      friendly_name: 'Detekce otevřeného okna – severní pokoj (druhé patro)'
      entity_id: sensor.second_floor_north_room_temp
      sample_duration: 7200
      min_gradient: -0.001
      max_samples: 240
      device_class: window
    second_floor_detection_of_open_window_middle_room:
      friendly_name: 'Detekce otevřeného okna – střední pokoj (druhé patro)'
      entity_id: sensor.second_floor_middle_room_temp
      sample_duration: 7200
      min_gradient: -0.001
      max_samples: 240
      device_class: window
    second_floor_detection_of_open_window_corner_room:
      friendly_name: 'Detekce otevřeného okna – rohový pokoj (druhé patro)'
      entity_id: sensor.second_floor_corner_room_temp
      sample_duration: 7200
      min_gradient: -0.001
      max_samples: 240
      device_class: window
    second_floor_detection_of_open_window_corridor_and_toilet:
      friendly_name: 'Detekce otevřeného okna – chodba a toaleta (druhé patro)'
      entity_id: sensor.second_floor_corridor_and_toilet_temp
      sample_duration: 7200
      min_gradient: -0.001
      max_samples: 240
      device_class: window
    second_floor_detection_of_open_window_parents_bedroom:
      friendly_name: 'Detekce otevřeného okna – ložnice rodičů (druhé patro)'
      entity_id: sensor.second_floor_parents_bedroom_temp
      sample_duration: 7200
      min_gradient: -0.001
      max_samples: 240
      device_class: window